### ISSUE TITLE
Support sorting of columns

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes-protein-atlas-tissue-expression-visualizer#11]
Similar to the version present on the old webapp (https://www.humanmine.org/humanmine/report.do?id=1062390&trail=%7c1062390), it would be useful to have a small button beside each column which allowed you to sort the rows.

**Comment by kseniabelyavce** [comment]
I'll take the issue then!

**Comment by heralden** [comment]
Assigned. Please go ahead [=

**Comment by heralden** [comment]
Resolved with #13
